### PR TITLE
Port to Yocto 2.1

### PR DESCRIPTION
**Pull request by zeenix**
getVar() now requires the expand parameter:

http://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#migration-2.1-expand-parameter-to-getvar-and-getvarflag-now-mandatory

### CODE REVIEW

**Comment by klihub** [comment]
Hmm... in Yocto 2.3 and later which I use as baseline, getVar and getVarFlag default to expansion if not specified. IOW, those explicitly stated False's should be changed to True's. Do you want to update the patch, or do you want me to do it ?

**Comment by zeenix** [comment]
@klihub Are you sure? According to the docs this parameter has been mandatory since 2.1 (and didn't become optional after) so there is no default value after 2.1. Also the docs say as first thing:

> The expand parameter to getVar() and getVarFlag() previously defaulted to False if not specified.

FWIW, I'm also on 2.3 and the build was successful with these changes, haven't really tested it to run/work though.

**Comment by klihub** [comment]
The notes in the docs you linked to say: "The reason for this change is that it prepares the way for changing the default to True in a future Yocto Project release."
Well, that change has happened:
```
dexter bitbake $ grep '^[ \t]*def getVar' lib/bb/data_smart.py 
    def getVar(self, var, expand=True, noweakdefault=False, parsing=False):
    def getVarFlag(self, var, flag, expand=True, noweakdefault=False, parsing=False):
    def getVarFlags(self, var, expand = False, internalflags=False):
```
Here's the bugzilla entry for the related change/feature in 2.3:
https://bugzilla.yoctoproject.org/show_bug.cgi?id=10679

And here's patch that removed the now-default True argument en masse:
http://lists.openembedded.org/pipermail/bitbake-devel/2016-November/008250.html

I'll merge your patch modifying those False's to True's if that's ok with you.

**Comment by zeenix** [comment]
Ah ok, weird they don't mention in the docs then. Thanks.

**Comment by klihub** [comment]
Yes, the docs look to be out of sync. Anyway, I merged and pushed your patch edited accordingly. Just drop the original and rebase on the edited 23fd69dccc695b4cc22ef2511116ece2bc65a20d one.

**Comment by zeenix** [comment]
Thanks!

**Pull request closed without merging**
